model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.SRDiffusion
  params:
    linear_start: 0.0001
    linear_end: 0.015
    log_every_t: 100
    timesteps: 1000
    first_stage_key: image_hr
    cond_stage_key: image_lr
    image_size: 32
    channels: 64
    inp_size: 256
    default_output_size: 256
    c_encode: True
    conditioning_key: concat
    concat_mode: True
    cond_stage_trainable: False
    monitor: val/loss_simple_ema
    scale_by_std: True
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 32
        out_channels: 32
        model_channels: 256
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        num_heads: 4
        
    first_stage_config:
      target: ldm.models.firststagemodel.FirstStageModel
      params:
        ckpt_path: logs/2026-01-05T18-09-39_first_stage_sr_32_256/checkpoints/epoch=000534.ckpt # first_stage_model checkpoint
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: True
          z_channels: 32
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

        liifconfig:
          hidden_list: [256, 256, 256, 256]
          cell_decode: True
          local_ensemble: True

    cond_stage_config:
      target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: ldm.data.datasets.CTSRTrain
      params:
        size: 256
        lr_size: 32
    validation:
      target: ldm.data.datasets.CTSRValidation
      params:
        size: 256
        lr_size: 32
        first_k: 100

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_images_kwargs:
          plot_denoise_rows: True
